### ISSUE TITLE
Available boards?

### ISSUE THREAD

**Issue by janrinze** [maikmerten/hx8k-breakout-extension#1]
I was wondering if there are assembled boards available.
Nice board, would love to run some tests on it.

**Comment by maikmerten** [comment]
I think I still have one unpopulated PCB somewhere and necessary parts, so I can part with one assembled board for cost of shipping. I don't plan to make assembled boards generally available, but looking at your github repos, it seems you're interested in open-source FPGA designs, so I'll happily support that. Just be aware that the board comes with no warranty whatsoever and that my soldering is not up to factory standards ;-)

Feel free to contact me at maikmerten (at) googlemail (dot) com.

**Comment by janrinze** [comment]
email sent.
looking forward to test it :-)

**Comment by maikmerten** [comment]
Email received, will close the issue here.
